# This is generated file.

components:
    schemas:
        response-for-paths--ue-authentications-{authCtxId}-eap-session-post-responses-200-application-3gppHal+json:
            additionalProperties: true
            properties:
                _links:
                    additionalProperties:
                        $ref: TS29571_CommonData.yaml#/components/schemas/LinksValueSchema
                    description: 'URI : /{eapSessionUri}'
                    minProperties: 1
                    type: object
                eapPayload:
                    $ref: TS29571_CommonData.yaml#/components/schemas/EapPayload
            required:
                - eapPayload
                - _links
            type: object
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        nausf-auth: Access to Nausf_UEAuthentication API
externalDocs:
    description: 3GPP TS 29.509 V16.9.0; 5G System; 3GPP TS Authentication Server services.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.509
info:
    description: |
        AUSF UE Authentication Service.
        © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: AUSF API
    version: 1.1.3
openapi: 3.0.0
paths:
    /rg-authentications:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/RgAuthenticationInfo
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ausf-RgAuthCtx
                    description: RgAuthCtx
                    headers:
                        Location:
                            description: 'Contains the URI of the newly created resource according to the structure: {apiRoot}/nausf-auth/v1/rg-authentications/{authCtxId}'
                            required: true
                            schema:
                                type: string
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Bad Request from the AMF
                "403":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: The UE is not allowed to be authenticated
                "404":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: User does not exist in the HPLMN
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: ""
    /ue-authentications:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/AuthenticationInfo
                required: true
            responses:
                "201":
                    content:
                        application/3gppHal+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/UEAuthenticationCtx
                    description: UEAuthenticationCtx
                    headers:
                        Location:
                            description: 'Contains the URI of the newly created resource according to the structure: {apiRoot}/nausf-auth/v1/ue-authentications/{authCtxId}'
                            required: true
                            schema:
                                type: string
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Bad Request from the AMF
                "403":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Forbidden due to serving network not authorized
                "404":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: User does not exist in the HPLMN
                "500":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Internal Server Error
                "501":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Received protection scheme is not supported by HPLMN
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: ""
    /ue-authentications/{authCtxId}/5g-aka-confirmation:
        put:
            parameters:
                - in: path
                  name: authCtxId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/ConfirmationData
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ConfirmationDataResponse
                    description: Request processed (EAP success or Failure)
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Bad Request
                "500":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Internal Server Error
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: ""
        delete:
            operationId: Delete5gAkaAuthenticationResult
            parameters:
                - in: path
                  name: authCtxId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: Expected response to a successful authentication result removal
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Deletes the authentication result in the UDM
            tags:
                - Authentication Result Deletion
    /ue-authentications/{authCtxId}/eap-session:
        post:
            operationId: EapAuthMethod
            parameters:
                - in: path
                  name: authCtxId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/EapSession
            responses:
                "200":
                    content:
                        application/3gppHal+json:
                            schema:
                                $ref: '#/components/schemas/response-for-paths--ue-authentications-{authCtxId}-eap-session-post-responses-200-application-3gppHal+json'
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/EapSession
                    description: Use to handle or close the EAP session
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Bad Request
                "500":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Internal Server Error
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: ""
        delete:
            operationId: DeleteEapAuthenticationResult
            parameters:
                - in: path
                  name: authCtxId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: Expected response to a successful authentication result removal
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Deletes the authentication result in the UDM
            tags:
                - Authentication Result Deletion
    /ue-authentications/deregister:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/DeregistrationInfo
                required: true
            responses:
                "204":
                    description: Expected response to a successful removal of security context
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: ""
security:
    - {}
    - oAuth2ClientCredentials:
        - nausf-auth
servers:
    - url: '{apiRoot}/nausf-auth/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.
