components:
    headers:
        cache-control:
            required: true
            schema:
                enum:
                    - no-store
                type: string
        pragma:
            required: true
            schema:
                enum:
                    - no-cache
                type: string
    schemas:
        AccessTokenClaims:
            additionalProperties: true
            description: The claims data structure for the access token
            properties:
                aud:
                    anyOf:
                        - $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/NFType
                        - items:
                            $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                          minItems: 1
                          type: array
                consumerPlmnId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
                exp:
                    type: integer
                iss:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                producerNfSetId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfSetId
                producerNsiList:
                    items:
                        type: string
                    minItems: 1
                    type: array
                producerPlmnId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
                producerSnssaiList:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
                    minItems: 1
                    type: array
                scope:
                    pattern: ^([a-zA-Z0-9_:-]+)( [a-zA-Z0-9_:-]+)*$
                    type: string
                sub:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
            required:
                - iss
                - sub
                - aud
                - scope
                - exp
            type: object
        AccessTokenErr:
            additionalProperties: true
            description: Error returned in the access token response message
            properties:
                error:
                    enum:
                        - invalid_request
                        - invalid_client
                        - invalid_grant
                        - unauthorized_client
                        - unsupported_grant_type
                        - invalid_scope
                    type: string
                error_description:
                    type: string
                error_uri:
                    type: string
            required:
                - error
            type: object
        AccessTokenReq:
            additionalProperties: true
            description: Contains information related to the access token request
            properties:
                grant_type:
                    enum:
                        - client_credentials
                    type: string
                nfInstanceId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                nfType:
                    $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/NFType
                requesterFqdn:
                    $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/Fqdn
                requesterPlmn:
                    $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
                requesterPlmnList:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
                    minItems: 2
                    type: array
                requesterSnpnList:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/PlmnIdNid
                    minItems: 1
                    type: array
                requesterSnssaiList:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
                    minItems: 1
                    type: array
                scope:
                    pattern: ^([a-zA-Z0-9_:-]+)( [a-zA-Z0-9_:-]+)*$
                    type: string
                targetNfInstanceId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                targetNfServiceSetId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfServiceSetId
                targetNfSetId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfSetId
                targetNfType:
                    $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/NFType
                targetNsiList:
                    items:
                        type: string
                    minItems: 1
                    type: array
                targetPlmn:
                    $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
                targetSnssaiList:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
                    minItems: 1
                    type: array
            required:
                - grant_type
                - nfInstanceId
                - scope
            type: object
        AccessTokenRsp:
            additionalProperties: true
            description: Contains information related to the access token response
            properties:
                access_token:
                    description: JWS Compact Serialized representation of JWS signed JSON object (AccessTokenClaims)
                    type: string
                expires_in:
                    type: integer
                scope:
                    pattern: ^([a-zA-Z0-9_:-]+)( [a-zA-Z0-9_:-]+)*$
                    type: string
                token_type:
                    enum:
                        - Bearer
                    type: string
            required:
                - access_token
                - token_type
            type: object
externalDocs:
    description: 3GPP TS 29.510 V16.11.0; 5G System; Network Function Repository Services; Stage 3
    url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
info:
    description: "NRF OAuth2 Authorization.  \n© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
    title: NRF OAuth2
    version: 1.1.5
openapi: 3.0.0
paths:
    /oauth2/token:
        post:
            operationId: AccessTokenRequest
            parameters:
                - description: Content-Encoding, described in IETF RFC 7231
                  in: header
                  name: Content-Encoding
                  schema:
                    type: string
                - description: Accept-Encoding, described in IETF RFC 7231
                  in: header
                  name: Accept-Encoding
                  schema:
                    type: string
            requestBody:
                content:
                    application/x-www-form-urlencoded:
                        encoding:
                            requesterPlmn:
                                contentType: application/json
                            requesterPlmnList:
                                contentType: application/json
                            requesterSnpnList:
                                contentType: application/json
                            requesterSnssaiList:
                                contentType: application/json
                            targetNsiList:
                                explode: true
                                style: form
                            targetPlmn:
                                contentType: application/json
                            targetSnssaiList:
                                contentType: application/json
                        schema:
                            $ref: '#/components/schemas/AccessTokenReq'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccessTokenRsp'
                    description: Successful Access Token Request
                    headers:
                        Accept-Encoding:
                            description: Accept-Encoding, described in IETF RFC 7694
                            schema:
                                type: string
                        Cache-Control:
                            $ref: '#/components/headers/cache-control'
                        Content-Encoding:
                            description: Content-Encoding, described in IETF RFC 7231
                            schema:
                                type: string
                        Pragma:
                            $ref: '#/components/headers/pragma'
                "307":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/RedirectResponse
                    description: Temporary Redirect
                    headers:
                        Location:
                            description: The URI pointing to the resource located on the redirect target NRF
                            required: true
                            schema:
                                type: string
                "308":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/RedirectResponse
                    description: Permanent Redirect
                    headers:
                        Location:
                            description: The URI pointing to the resource located on the redirect target NRF
                            required: true
                            schema:
                                type: string
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AccessTokenErr'
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Error in the Access Token Request
                    headers:
                        Cache-Control:
                            $ref: '#/components/headers/cache-control'
                        Pragma:
                            $ref: '#/components/headers/pragma'
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "501":
                    $ref: TS29571_CommonData.yaml#/components/responses/501
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Access Token Request
            tags:
                - Access Token Request
