# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        nsmf-event-exposure: Access to the Nsmf_EventExposure API
externalDocs:
    description: 3GPP TS 29.508 V16.10.0; 5G System; Session Management Event Exposure Service.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.508/
info:
    description: |
        Session Management Event Exposure Service.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Nsmf_EventExposure
    version: 1.1.3
openapi: 3.0.0
paths:
    /subscriptions:
        post:
            callbacks:
                myNotification:
                    '{$request.body#/notifUri}':
                        post:
                            callbacks:
                                afAcknowledgement:
                                    '{request.body#/ackUri}':
                                        post:
                                            requestBody:
                                                content:
                                                    application/json:
                                                        schema:
                                                            $ref: TS29571_CommonData.yaml#/components/schemas/AckOfNotify
                                                required: true
                                            responses:
                                                "204":
                                                    description: No Content (successful acknowledgement)
                                                "307":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                                "308":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                                "400":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                                "401":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/401
                                                "403":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                                "404":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/404
                                                "411":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                                "413":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                                "415":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                                "429":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                                "500":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                                "503":
                                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                                default:
                                                    $ref: TS29571_CommonData.yaml#/components/responses/default
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/NsmfEventExposureNotification
                                required: true
                            responses:
                                "204":
                                    description: No Content, Notification was successful.
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                "401":
                                    $ref: TS29571_CommonData.yaml#/components/responses/401
                                "403":
                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                "404":
                                    $ref: TS29571_CommonData.yaml#/components/responses/404
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                default:
                                    $ref: TS29571_CommonData.yaml#/components/responses/default
            operationId: CreateIndividualSubcription
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/NsmfEventExposure
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/NsmfEventExposure
                    description: Created.
                    headers:
                        Location:
                            description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/nsmf-event-exposure/v1/subscriptions/{subId}'
                            required: true
                            schema:
                                type: string
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Create an individual subscription for event notifications from the SMF
            tags:
                - Subscriptions (Collection)
    /subscriptions/{subId}:
        get:
            operationId: GetIndividualSubcription
            parameters:
                - description: Event Subscription ID
                  in: path
                  name: subId
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/NsmfEventExposure
                    description: OK. Resource representation is returned
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29571_CommonData.yaml#/components/responses/406
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Read an individual subscription for event notifications from the SMF
            tags:
                - IndividualSubscription (Document)
        put:
            operationId: ReplaceIndividualSubcription
            parameters:
                - description: Event Subscription ID
                  in: path
                  name: subId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/NsmfEventExposure
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/NsmfEventExposure
                    description: OK. Resource was successfully modified and representation is returned
                "204":
                    description: No Content. Resource was successfully modified
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Replace an individual subscription for event notifications from the SMF
            tags:
                - IndividualSubscription (Document)
        delete:
            operationId: DeleteIndividualSubcription
            parameters:
                - description: Event Subscription ID
                  in: path
                  name: subId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: No Content. Resource was successfully deleted
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Delete an individual subscription for event notifications from the SMF
            tags:
                - IndividualSubscription (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - nsmf-event-exposure
servers:
    - url: '{apiRoot}/nsmf-event-exposure/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501
