# This is generated file.

components:
    schemas:
        NfGroupIdMapResult:
            additionalProperties:
                $ref: TS29571_CommonData.yaml#/components/schemas/NfGroupId
            minProperties: 1
            type: object
        SubscriberId:
            pattern: ^(imsi-[0-9]{5,15}|nai-.+|msisdn-[0-9]{5,15}|extid-[^@]+@[^@]+|impi-.+|impu-.+|.+)$
            type: string
            x-go-type-skip-optional-pointer: true
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        nudr-group-id-map: Access to the Nudr_GroupIDmap API
externalDocs:
    description: 3GPP TS 29.504 V16.10.0; 5G System; Unified Data Repository Services; Stage 3
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.504/
info:
    description: |
        Unified Data Repository Service for NF-Group ID retrieval.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Nudr_GroupIDmap
    version: 1.0.1
openapi: 3.0.0
paths:
    /nf-group-ids:
        get:
            operationId: GetNfGroupIDs
            parameters:
                - description: Type of NF
                  explode: false
                  in: query
                  name: nf-type
                  required: true
                  schema:
                    items:
                        $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/NFType
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                  style: form
                - description: Identifier of the subscriber
                  in: query
                  name: subscriberId
                  required: true
                  schema:
                    $ref: '#/components/schemas/SubscriberId'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/NfGroupIdMapResult'
                    description: Expected response to a valid request
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Retrieves NF-Group IDs for provided Subscriber and NF types
            tags:
                - NF Group IDs (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - nudr-group-id-map
servers:
    - description: API root
      url: '{apiRoot}/nudr-group-id-map/v1'
      variables:
        apiRoot:
            default: https://example.com
