components:
    schemas:
        AuthResult:
            enum:
                - AUTHENTICATION_SUCCESS
                - AUTHENTICATION_FAILURE
                - AUTHENTICATION_ONGOING
            type: string
            x-go-type-skip-optional-pointer: true
        AuthType:
            enum:
                - 5G_AKA
                - EAP_AKA_PRIME
                - EAP_TLS
            type: string
        AuthenticationInfo:
            additionalProperties: true
            properties:
                cellCagInfo:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/CagId
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                n5gcInd:
                    default: false
                    type: boolean
                pei:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Pei
                resynchronizationInfo:
                    $ref: TS29503_Nudm_UEAU.yaml#/components/schemas/ResynchronizationInfo
                routingIndicator:
                    pattern: ^[0-9]{1,4}$
                    type: string
                    x-go-type-skip-optional-pointer: true
                servingNetworkName:
                    $ref: TS29503_Nudm_UEAU.yaml#/components/schemas/ServingNetworkName
                supiOrSuci:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupiOrSuci
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
                traceData:
                    $ref: TS29571_CommonData.yaml#/components/schemas/TraceData
                udmGroupId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfGroupId
            required:
                - supiOrSuci
                - servingNetworkName
            type: object
        Av5gAka:
            additionalProperties: true
            properties:
                autn:
                    $ref: TS29503_Nudm_UEAU.yaml#/components/schemas/Autn
                hxresStar:
                    $ref: '#/components/schemas/HxresStar'
                rand:
                    $ref: TS29503_Nudm_UEAU.yaml#/components/schemas/Rand
            required:
                - rand
                - hxresStar
                - autn
            type: object
        ConfirmationData:
            additionalProperties: true
            properties:
                resStar:
                    $ref: '#/components/schemas/ResStar'
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - resStar
            type: object
        ConfirmationDataResponse:
            additionalProperties: true
            properties:
                authResult:
                    $ref: '#/components/schemas/AuthResult'
                kseaf:
                    $ref: '#/components/schemas/Kseaf'
                supi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
            required:
                - authResult
            type: object
        DeregistrationInfo:
            additionalProperties: true
            properties:
                supi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - supi
            type: object
        EapPayload:
            description: contains an EAP packet
            format: base64
            nullable: true
            type: string
        EapSession:
            additionalProperties: true
            properties:
                _links:
                    additionalProperties:
                        $ref: TS29571_CommonData.yaml#/components/schemas/LinksValueSchema
                    type: object
                authResult:
                    $ref: '#/components/schemas/AuthResult'
                eapPayload:
                    $ref: '#/components/schemas/EapPayload'
                kSeaf:
                    $ref: '#/components/schemas/Kseaf'
                supi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - eapPayload
            type: object
        HxresStar:
            pattern: '[A-Fa-f0-9]{32}'
            type: string
            x-go-type-skip-optional-pointer: true
        Kseaf:
            pattern: '[A-Fa-f0-9]{64}'
            type: string
            x-go-type-skip-optional-pointer: true
        ResStar:
            nullable: true
            pattern: '[A-Fa-f0-9]{32}'
            type: string
        RgAuthCtx:
            additionalProperties: true
            properties:
                authInd:
                    default: false
                    type: boolean
                authResult:
                    $ref: '#/components/schemas/AuthResult'
                supi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
            required:
                - authResult
            type: object
        RgAuthenticationInfo:
            additionalProperties: true
            properties:
                authenticatedInd:
                    default: false
                    type: boolean
                suci:
                    $ref: '#/components/schemas/Suci'
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - suci
                - authenticatedInd
            type: object
        Suci:
            pattern: ^(suci-(0-[0-9]{3}-[0-9]{2,3}|[1-7]-.+)-[0-9]{1,4}-(0-0-.+|[a-fA-F1-9]-([1-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])-[a-fA-F0-9]+)|.+)$
            type: string
            x-go-type-skip-optional-pointer: true
        UEAuthenticationCtx:
            additionalProperties: true
            properties:
                _links:
                    additionalProperties:
                        $ref: TS29571_CommonData.yaml#/components/schemas/LinksValueSchema
                    type: object
                5gAuthData:
                    oneOf:
                        - $ref: '#/components/schemas/Av5gAka'
                        - $ref: '#/components/schemas/EapPayload'
                authType:
                    $ref: '#/components/schemas/AuthType'
                servingNetworkName:
                    $ref: TS29503_Nudm_UEAU.yaml#/components/schemas/ServingNetworkName
            required:
                - authType
                - 5gAuthData
                - _links
            type: object
    securitySchemes:
        oAuth2ClientCredentials:
            flows:
                clientCredentials:
                    scopes:
                        nausf-auth: Access to Nausf_UEAuthentication API
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
            type: oauth2
externalDocs:
    description: 3GPP TS 29.509 V16.9.0; 5G System; 3GPP TS Authentication Server services.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.509
info:
    description: |
        AUSF UE Authentication Service.
        © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: AUSF API
    version: 1.1.3
openapi: 3.0.0
paths:
    /rg-authentications:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RgAuthenticationInfo'
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RgAuthCtx'
                    description: RgAuthCtx
                    headers:
                        Location:
                            description: 'Contains the URI of the newly created resource according to the structure: {apiRoot}/nausf-auth/v1/rg-authentications/{authCtxId}'
                            required: true
                            schema:
                                type: string
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Bad Request from the AMF
                "403":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: The UE is not allowed to be authenticated
                "404":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: User does not exist in the HPLMN
    /ue-authentications:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AuthenticationInfo'
                required: true
            responses:
                "201":
                    content:
                        application/3gppHal+json:
                            schema:
                                $ref: '#/components/schemas/UEAuthenticationCtx'
                    description: UEAuthenticationCtx
                    headers:
                        Location:
                            description: 'Contains the URI of the newly created resource according to the structure: {apiRoot}/nausf-auth/v1/ue-authentications/{authCtxId}'
                            required: true
                            schema:
                                type: string
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Bad Request from the AMF
                "403":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Forbidden due to serving network not authorized
                "404":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: User does not exist in the HPLMN
                "500":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Internal Server Error
                "501":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Received protection scheme is not supported by HPLMN
    /ue-authentications/{authCtxId}/5g-aka-confirmation:
        delete:
            operationId: Delete5gAkaAuthenticationResult
            parameters:
                - in: path
                  name: authCtxId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: Expected response to a successful authentication result removal
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Deletes the authentication result in the UDM
            tags:
                - Authentication Result Deletion
        put:
            parameters:
                - in: path
                  name: authCtxId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ConfirmationData'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ConfirmationDataResponse'
                    description: Request processed (EAP success or Failure)
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Bad Request
                "500":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Internal Server Error
    /ue-authentications/{authCtxId}/eap-session:
        delete:
            operationId: DeleteEapAuthenticationResult
            parameters:
                - in: path
                  name: authCtxId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: Expected response to a successful authentication result removal
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Deletes the authentication result in the UDM
            tags:
                - Authentication Result Deletion
        post:
            operationId: EapAuthMethod
            parameters:
                - in: path
                  name: authCtxId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/EapSession'
            responses:
                "200":
                    content:
                        application/3gppHal+json:
                            schema:
                                additionalProperties: true
                                properties:
                                    _links:
                                        additionalProperties:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/LinksValueSchema
                                        description: 'URI : /{eapSessionUri}'
                                        minProperties: 1
                                        type: object
                                    eapPayload:
                                        $ref: '#/components/schemas/EapPayload'
                                required:
                                    - eapPayload
                                    - _links
                                type: object
                        application/json:
                            schema:
                                $ref: '#/components/schemas/EapSession'
                    description: Use to handle or close the EAP session
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Bad Request
                "500":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Internal Server Error
    /ue-authentications/deregister:
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeregistrationInfo'
                required: true
            responses:
                "204":
                    description: Expected response to a successful removal of security context
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
security:
    - {}
    - oAuth2ClientCredentials:
        - nausf-auth
servers:
    - url: '{apiRoot}/nausf-auth/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.
