# This is generated file.

components:
    schemas:
        AdditionInfoEnableUeReachability:
            additionalProperties: true
            properties:
                maxWaitingTime:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DurationSec
            type: object
        EnableUeReachabilityReqData:
            additionalProperties: true
            properties:
                extBufSupport:
                    default: false
                    type: boolean
                oldGuami:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Guami
                reachability:
                    $ref: TS29518_Namf_EventExposure.yaml#/components/schemas/UeReachability
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - reachability
            type: object
        EnableUeReachabilityRspData:
            additionalProperties: true
            properties:
                reachability:
                    $ref: TS29518_Namf_EventExposure.yaml#/components/schemas/UeReachability
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - reachability
            type: object
        ProblemDetailsEnableUeReachability:
            allOf:
                - $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                - $ref: '#/components/schemas/AdditionInfoEnableUeReachability'
        UeContextInfo:
            additionalProperties: true
            properties:
                accessType:
                    $ref: TS29571_CommonData.yaml#/components/schemas/AccessType
                lastActTime:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DateTime
                ratType:
                    $ref: TS29571_CommonData.yaml#/components/schemas/RatType
                supportVoPS:
                    type: boolean
                supportVoPSn3gpp:
                    type: boolean
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            type: object
        UeContextInfoClass:
            enum:
                - TADS
            type: string
    securitySchemes:
        oAuth2ClientCredentials:
            flows:
                clientCredentials:
                    scopes:
                        namf-mt: Access to the Namf_MT API
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
            type: oauth2
externalDocs:
    description: 3GPP TS 29.518 V16.10.0; 5G System; Access and Mobility Management Services
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
info:
    description: |
        AMF Mobile Terminated Service
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Namf_MT
    version: 1.1.3
openapi: 3.0.0
paths:
    /ue-contexts/{ueContextId}:
        get:
            operationId: Provide Domain Selection Info
            parameters:
                - description: UE Context Identifier
                  in: path
                  name: ueContextId
                  required: true
                  schema:
                    pattern: ^(imsi-[0-9]{5,15}|nai-.+|gli-.+|gci-.+|.+)$
                    type: string
                    x-go-type-skip-optional-pointer: true
                - description: UE Context Information Class
                  in: query
                  name: info-class
                  schema:
                    $ref: '#/components/schemas/UeContextInfoClass'
                - description: Supported Features
                  in: query
                  name: supported-features
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
                - content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/Guami
                  description: Old GUAMI
                  in: query
                  name: old-guami
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UeContextInfo'
                    description: Requested UE Context Information returned
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "414":
                    $ref: TS29571_CommonData.yaml#/components/responses/414
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Namf_MT Provide Domain Selection Info service Operation
            tags:
                - ueContext (Document)
    /ue-contexts/{ueContextId}/ue-reachind:
        put:
            operationId: EnableUeReachability
            parameters:
                - description: UE Context Identifier
                  in: path
                  name: ueContextId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/EnableUeReachabilityReqData'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/EnableUeReachabilityRspData'
                    description: UE has become reachable as desired
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ProblemDetailsEnableUeReachability'
                    description: Forbidden
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                "504":
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ProblemDetailsEnableUeReachability'
                    description: Gateway Timeout
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Namf_MT EnableUEReachability service Operation
            tags:
                - ueReachInd (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - namf-mt
servers:
    - url: '{apiRoot}/namf-mt/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501
