# This is generated file.

components:
    securitySchemes:
        oAuth2Clientcredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        npcf-smpolicycontrol: Access to the Npcf_SMPolicyControl API
externalDocs:
    description: 3GPP TS 29.512 V16.17.0; 5G System; Session Management Policy Control Service.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.512/
info:
    description: |
        Session Management Policy Control Service
        © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Npcf_SMPolicyControl API
    version: 1.1.9
openapi: 3.0.0
paths:
    /sm-policies:
        post:
            callbacks:
                SmPolicyControlTerminationRequestNotification:
                    '{$request.body#/notificationUri}/terminate':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/TerminationNotification
                                required: true
                            responses:
                                "204":
                                    description: No Content, Notification was successful
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                "401":
                                    $ref: TS29571_CommonData.yaml#/components/responses/401
                                "403":
                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                "404":
                                    $ref: TS29571_CommonData.yaml#/components/responses/404
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                default:
                                    $ref: TS29571_CommonData.yaml#/components/responses/default
                SmPolicyUpdateNotification:
                    '{$request.body#/notificationUri}/update':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/SmPolicyNotification
                                required: true
                            responses:
                                "200":
                                    content:
                                        application/json:
                                            schema:
                                                oneOf:
                                                    - $ref: TS29571_CommonData.yaml#/components/schemas/UeCampingRep
                                                    - items:
                                                        $ref: TS29571_CommonData.yaml#/components/schemas/PartialSuccessReport
                                                      minItems: 1
                                                      type: array
                                                      x-go-type-skip-optional-pointer: true
                                                    - items:
                                                        $ref: TS29571_CommonData.yaml#/components/schemas/PolicyDecisionFailureCode
                                                      minItems: 1
                                                      type: array
                                                      x-go-type-skip-optional-pointer: true
                                    description: OK. The current applicable values corresponding to the policy control request trigger is reported
                                "204":
                                    description: No Content, Notification was succesfull
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    content:
                                        application/json:
                                            schema:
                                                $ref: TS29571_CommonData.yaml#/components/schemas/ErrorReport
                                    description: Bad Request.
                                "401":
                                    $ref: TS29571_CommonData.yaml#/components/responses/401
                                "403":
                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                "404":
                                    $ref: TS29571_CommonData.yaml#/components/responses/404
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                default:
                                    $ref: TS29571_CommonData.yaml#/components/responses/default
            operationId: CreateSMPolicy
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/SmPolicyContextData
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/SmPolicyDecision
                    description: Created
                    headers:
                        Location:
                            description: Contains the URI of the newly created resource
                            required: true
                            schema:
                                type: string
                "308":
                    description: Permanent Redirect
                    headers:
                        Location:
                            description: 'Contains the URI of the PCF within the existing PCF binding information stored in the BSF for the same UE ID, S-NSSAI and DNN combination '
                            required: true
                            schema:
                                type: string
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    description: Not Found
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Create a new Individual SM Policy
            tags:
                - SM Policies (Collection)
    /sm-policies/{smPolicyId}:
        get:
            operationId: GetSMPolicy
            parameters:
                - description: Identifier of a policy association
                  in: path
                  name: smPolicyId
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/SmPolicyControl
                    description: OK. Resource representation is returned
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29571_CommonData.yaml#/components/responses/406
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Read an Individual SM Policy
            tags:
                - Individual SM Policy (Document)
    /sm-policies/{smPolicyId}/delete:
        post:
            operationId: DeleteSMPolicy
            parameters:
                - description: Identifier of a policy association
                  in: path
                  name: smPolicyId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/SmPolicyDeleteData
                required: true
            responses:
                "204":
                    description: No content
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Delete an existing Individual SM Policy
            tags:
                - Individual SM Policy (Document)
    /sm-policies/{smPolicyId}/update:
        post:
            operationId: UpdateSMPolicy
            parameters:
                - description: Identifier of a policy association
                  in: path
                  name: smPolicyId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/SmPolicyUpdateContextData
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/SmPolicyDecision
                    description: OK. Updated policies are returned
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Update an existing Individual SM Policy
            tags:
                - Individual SM Policy (Document)
security:
    - {}
    - oAuth2Clientcredentials:
        - npcf-smpolicycontrol
servers:
    - url: '{apiRoot}/npcf-smpolicycontrol/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501
