# This is generated file.

components:
    schemas:
        5GSrvccInfo:
            additionalProperties: true
            properties:
                cMsisdn:
                    $ref: TS29571_CommonData.yaml#/components/schemas/CMsisdn
                stnSr:
                    $ref: TS29571_CommonData.yaml#/components/schemas/StnSr
                ue5GSrvccCapability:
                    type: boolean
            required:
                - ue5GSrvccCapability
            type: object
        LocationInfoRequest:
            additionalProperties: true
            properties:
                req5gsLoc:
                    default: false
                    type: boolean
                reqCurrentLoc:
                    default: false
                    type: boolean
                reqRatType:
                    default: false
                    type: boolean
                reqServingNode:
                    default: false
                    type: boolean
                reqTimeZone:
                    default: false
                    type: boolean
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            type: object
        LocationInfoResult:
            additionalProperties: true
            properties:
                amfInstanceId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                currentLoc:
                    type: boolean
                ecgi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ecgi
                geoInfo:
                    description: Original reference TS29572_Nlmf_Location.yaml#/components/schemas/GeographicArea
                    x-go-type-skip-optional-pointer: true
                locationAge:
                    description: Original reference TS29572_Nlmf_Location.yaml#/components/schemas/AgeOfLocationEstimate
                    x-go-type-skip-optional-pointer: true
                ncgi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ncgi
                ratType:
                    $ref: TS29571_CommonData.yaml#/components/schemas/RatType
                smsfInstanceId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
                tai:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Tai
                timezone:
                    $ref: TS29571_CommonData.yaml#/components/schemas/TimeZone
                vPlmnId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
            type: object
        UeInfo:
            additionalProperties: true
            properties:
                5gSrvccInfo:
                    $ref: '#/components/schemas/5GSrvccInfo'
                tadsInfo:
                    $ref: TS29518_Namf_MT.yaml#/components/schemas/UeContextInfo
                userState:
                    $ref: TS29518_Namf_EventExposure.yaml#/components/schemas/5GsUserState
            type: object
    securitySchemes:
        oAuth2ClientCredentials:
            flows:
                clientCredentials:
                    scopes:
                        nudm-mt: Access to the nudm-mt API
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
            type: oauth2
externalDocs:
    description: 3GPP TS 29.503 Unified Data Management Services, version 16.10.0
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
info:
    description: |
        UDM MT Service.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Nudm_MT
    version: 1.0.2
openapi: 3.0.0
paths:
    /{supi}:
        get:
            operationId: QueryUeInfo
            parameters:
                - description: Identifier of the UE
                  in: path
                  name: supi
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
                - description: attributes to be retrieved
                  explode: false
                  in: query
                  name: fields
                  required: true
                  schema:
                    items:
                        type: string
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                  style: form
                - description: Supported Features
                  in: query
                  name: supported-features
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/UeInfo'
                    description: Expected response to a valid request
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "501":
                    $ref: TS29571_CommonData.yaml#/components/responses/501
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Query Information for the UE
            tags:
                - Query UE Info
    /{supi}/loc-info/provide-loc-info:
        post:
            operationId: ProvideLocationInfo
            parameters:
                - description: Identifier of the UE
                  in: path
                  name: supi
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LocationInfoRequest'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/LocationInfoResult'
                    description: Expected response to a valid request
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "501":
                    $ref: TS29571_CommonData.yaml#/components/responses/501
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Provides the UE's 5GS location information
            tags:
                - Provide UE Location
security:
    - oAuth2ClientCredentials:
        - nudm-mt
    - {}
servers:
    - url: '{apiRoot}/nudm-mt/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.
