# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        nnssf-nsselection: Access to the Nnssf_NSSelection API
externalDocs:
    description: 3GPP TS 29.531 V16.7.0; 5G System; Network Slice Selection Services; Stage 3
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.531/
info:
    description: |
        NSSF Network Slice Selection Service.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: NSSF NS Selection
    version: 2.1.2
openapi: 3.0.0
paths:
    /network-slice-information:
        get:
            operationId: NSSelectionGet
            parameters:
                - description: NF type of the NF service consumer
                  in: query
                  name: nf-type
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NFType
                - description: NF Instance ID of the NF service consumer
                  in: query
                  name: nf-id
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                - content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/SliceInfoForRegistration
                  description: Requested network slice information during Registration procedure
                  in: query
                  name: slice-info-request-for-registration
                - content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/SliceInfoForPDUSession
                  description: Requested network slice information during PDU session establishment procedure
                  in: query
                  name: slice-info-request-for-pdu-session
                - content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/SliceInfoForUEConfigurationUpdate
                  description: Requested network slice information during UE confuguration update procedure
                  in: query
                  name: slice-info-request-for-ue-cu
                - content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
                  description: PLMN ID of the HPLMN
                  in: query
                  name: home-plmn-id
                - content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/Tai
                  description: TAI of the UE
                  in: query
                  name: tai
                - description: Features required to be supported by the NFs in the target slice instance
                  in: query
                  name: supported-features
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/AuthorizedNetworkSliceInfo
                    description: OK (Successful Network Slice Selection)
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29571_CommonData.yaml#/components/responses/406
                "414":
                    $ref: TS29571_CommonData.yaml#/components/responses/414
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Retrieve the Network Slice Selection Information
            tags:
                - Network Slice Information (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - nnssf-nsselection
servers:
    - url: '{apiRoot}/nnssf-nsselection/v2'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause 4.4 of 3GPP TS 29.501
