# This is generated file.

components:
    responses:
        "307":
            description: Temporary Redirect
            headers:
                Location:
                    description: An alternative URI of the resource.
                    required: true
                    schema:
                        type: string
        "308":
            description: Permanent Redirect
            headers:
                Location:
                    description: An alternative URI of the resource.
                    required: true
                    schema:
                        type: string
        "400":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Bad request
        "401":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Unauthorized
        "403":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Forbidden
        "404":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Not Found
        "406":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Not Acceptable
        "409":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Conflict
        "411":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Length Required
        "412":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Precondition Failed
        "413":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Payload Too Large
        "414":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: URI Too Long
        "415":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Unsupported Media Type
        "429":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Too Many Requests
        "500":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Internal Server Error
        "503":
            content:
                application/problem+json:
                    schema:
                        $ref: TS29571_CommonData.yaml#/components/schemas/TS29122-ProblemDetails
            description: Service Unavailable
        default:
            description: Generic Error
externalDocs:
    description: 3GPP TS 29.122 V16.9.0 T8 reference point for Northbound APIs
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.122/
info:
    description: |
        Data types applicable to several APIs.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: TS 29.122 Common Data Types
    version: 1.1.1
openapi: 3.0.0
paths: {}
