components:
    schemas:
        BindingLevel:
            description: |
                Possible values are - "NF_SET" - "NF_INSTANCE"
            enum:
                - NF_SET
                - NF_INSTANCE
            type: string
        BindingResp:
            additionalProperties: true
            properties:
                pcfSmFqdn:
                    $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/Fqdn
                pcfSmIpEndPoints:
                    description: IP end points of the PCF hosting the Npcf_SMPolicyControl service.
                    items:
                        $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/IpEndPoint
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
            type: object
        ExtProblemDetails:
            allOf:
                - $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                - $ref: '#/components/schemas/BindingResp'
        ParameterCombination:
            additionalProperties: true
            properties:
                dnn:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Dnn
                snssai:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
                supi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
            type: object
        PcfBinding:
            additionalProperties: true
            properties:
                addIpv6Prefixes:
                    description: The additional IPv6 Address Prefixes of the served UE.
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Ipv6Prefix
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                addMacAddrs:
                    description: The additional MAC Addresses of the served UE.
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/MacAddr48
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                bindLevel:
                    $ref: '#/components/schemas/BindingLevel'
                dnn:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Dnn
                gpsi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Gpsi
                ipDomain:
                    type: string
                ipv4Addr:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ipv4Addr
                ipv4FrameRouteList:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Ipv4AddrMask
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                ipv6FrameRouteList:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Ipv6Prefix
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                ipv6Prefix:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ipv6Prefix
                macAddr48:
                    $ref: TS29571_CommonData.yaml#/components/schemas/MacAddr48
                paraCom:
                    $ref: '#/components/schemas/ParameterCombination'
                pcfDiamHost:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DiameterIdentity
                pcfDiamRealm:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DiameterIdentity
                pcfFqdn:
                    $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/Fqdn
                pcfId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                pcfIpEndPoints:
                    description: IP end points of the PCF hosting the Npcf_PolicyAuthorization service.
                    items:
                        $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/IpEndPoint
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                pcfSetId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfSetId
                pcfSmFqdn:
                    $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/Fqdn
                pcfSmIpEndPoints:
                    description: IP end points of the PCF hosting the Npcf_SMPolicyControl service.
                    items:
                        $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/IpEndPoint
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                recoveryTime:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DateTime
                snssai:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
                supi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
                suppFeat:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - dnn
                - snssai
            type: object
        PcfBindingPatch:
            additionalProperties: true
            properties:
                addIpv6Prefixes:
                    description: The additional IPv6 Address Prefixes of the served UE.
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Ipv6Prefix
                    minItems: 1
                    nullable: true
                    type: array
                addMacAddrs:
                    description: The additional MAC Addresses of the served UE.
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/MacAddr48
                    minItems: 1
                    nullable: true
                    type: array
                ipDomain:
                    nullable: true
                    type: string
                ipv4Addr:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ipv4AddrRm
                ipv6Prefix:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ipv6PrefixRm
                macAddr48:
                    $ref: TS29571_CommonData.yaml#/components/schemas/MacAddr48Rm
                pcfDiamHost:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DiameterIdentity
                pcfDiamRealm:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DiameterIdentity
                pcfFqdn:
                    $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/Fqdn
                pcfId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/NfInstanceId
                pcfIpEndPoints:
                    description: IP end points of the PCF hosting the Npcf_PolicyAuthorization service.
                    items:
                        $ref: TS29510_Nnrf_NFManagement.yaml#/components/schemas/IpEndPoint
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
            type: object
    securitySchemes:
        oAuth2ClientCredentials:
            flows:
                clientCredentials:
                    scopes:
                        nbsf-management: Access to the Nbsf_Management API
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
            type: oauth2
externalDocs:
    description: 3GPP TS 29.521 V16.8.0; 5G System; Binding Support Management Service.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.521/
info:
    description: |
        Binding Support Management Service API.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Nbsf_Management
    version: 1.1.2
openapi: 3.0.0
paths:
    /pcfBindings:
        get:
            operationId: GetPCFBindings
            parameters:
                - description: The IPv4 Address of the served UE.
                  in: query
                  name: ipv4Addr
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ipv4Addr
                - description: The IPv6 Address of the served UE. The NF service consumer shall append '/128' to the IPv6 address in the attribute value. E.g. '2001:db8:85a3::8a2e:370:7334/128'.
                  in: query
                  name: ipv6Prefix
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ipv6Prefix
                - description: The MAC Address of the served UE.
                  in: query
                  name: macAddr48
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/MacAddr48
                - description: DNN.
                  in: query
                  name: dnn
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Dnn
                - description: Subscription Permanent Identifier.
                  in: query
                  name: supi
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
                - description: Generic Public Subscription Identifier
                  in: query
                  name: gpsi
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Gpsi
                - content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
                  description: The identification of slice.
                  in: query
                  name: snssai
                - description: The IPv4 address domain identifier.
                  in: query
                  name: ipDomain
                  schema:
                    type: string
                - description: To filter irrelevant responses related to unsupported features
                  in: query
                  name: supp-feat
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PcfBinding'
                    description: The individual PCF session binding session binding information resource matching the query parameter(s) is returned.
                "204":
                    description: There is no PCF session binding information matching the query parameter(s).
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29571_CommonData.yaml#/components/responses/406
                "414":
                    $ref: TS29571_CommonData.yaml#/components/responses/414
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Read PCF Bindings information
            tags:
                - PCF Bindings (Collection)
        post:
            operationId: CreatePCFBinding
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PcfBinding'
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PcfBinding'
                    description: The creation of an individual PCF session binding.
                    headers:
                        Location:
                            description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/nbsf-management/v1/pcfBindings/{bindingId}'
                            required: true
                            schema:
                                type: string
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    content:
                        application/problem+json:
                            schema:
                                $ref: '#/components/schemas/ExtProblemDetails'
                    description: The existing PCF binding information stored in the BSF for the indicated combination is returned.
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Create a new Individual PCF binding information
            tags:
                - PCF Bindings (Collection)
    /pcfBindings/{bindingId}:
        delete:
            operationId: DeleteIndPCFBinding
            parameters:
                - description: Represents the individual PCF Session Binding.
                  in: path
                  name: bindingId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: No Content. The Individual PCF session binding information resource is deleted.
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Delete an existing Individual PCF Binding information
            tags:
                - Individual PCF Binding (Document)
        patch:
            operationId: UpdateIndPCFBinding
            parameters:
                - description: Represents the individual PCF Session Binding.
                  in: path
                  name: bindingId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/merge-patch+json:
                        schema:
                            $ref: '#/components/schemas/PcfBindingPatch'
                description: Parameters to update the existing session binding
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PcfBinding'
                    description: OK (Successful update of the session binding)
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Update an existing Individual PCF Binding information
            tags:
                - Individual PCF Binding (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - nbsf-management
servers:
    - url: '{apiRoot}/nbsf-management/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501.
