# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{tokenUrl}'
                    scopes: {}
externalDocs:
    description: 3GPP TS 29.522 V16.7.0; 5G System; Network Exposure Function Northbound APIs.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.522/
info:
    description: |
        API for AF traffic influence
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: 3gpp-traffic-influence
    version: 1.1.2
openapi: 3.0.0
paths:
    /{afId}/subscriptions:
        parameters:
            - description: Identifier of the AF
              in: path
              name: afId
              required: true
              schema:
                type: string
        get:
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: TS29571_CommonData.yaml#/components/schemas/TS29522-TrafficInfluSub
                                type: array
                    description: OK.
                "307":
                    $ref: TS29122_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29122_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29122_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29122_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29122_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29122_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29122_CommonData.yaml#/components/responses/406
                "429":
                    $ref: TS29122_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29122_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29122_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Generic Error
            summary: read all of the active subscriptions for the AF
            tags:
                - Traffic Influence Subscription
        post:
            callbacks:
                notificationDestination:
                    '{request.body#/notificationDestination}':
                        post:
                            callbacks:
                                afAcknowledgement:
                                    '{request.body#/afAckUri}':
                                        post:
                                            requestBody:
                                                content:
                                                    application/json:
                                                        schema:
                                                            $ref: TS29571_CommonData.yaml#/components/schemas/AfAckInfo
                                                required: true
                                            responses:
                                                "204":
                                                    description: No Content (successful acknowledgement)
                                                "307":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/307
                                                "308":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/308
                                                "400":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/400
                                                "401":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/401
                                                "403":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/403
                                                "404":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/404
                                                "411":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/411
                                                "413":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/413
                                                "415":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/415
                                                "429":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/429
                                                "500":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/500
                                                "503":
                                                    $ref: TS29122_CommonData.yaml#/components/responses/503
                                                default:
                                                    $ref: TS29122_CommonData.yaml#/components/responses/default
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/TS29522-EventNotification
                                required: true
                            responses:
                                "204":
                                    description: No Content (successful notification)
                                "307":
                                    $ref: TS29122_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29122_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29122_CommonData.yaml#/components/responses/400
                                "401":
                                    $ref: TS29122_CommonData.yaml#/components/responses/401
                                "403":
                                    $ref: TS29122_CommonData.yaml#/components/responses/403
                                "404":
                                    $ref: TS29122_CommonData.yaml#/components/responses/404
                                "411":
                                    $ref: TS29122_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29122_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29122_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29122_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29122_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29122_CommonData.yaml#/components/responses/503
                                default:
                                    $ref: TS29122_CommonData.yaml#/components/responses/default
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/TS29522-TrafficInfluSub
                description: Request to create a new subscription resource
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/TS29522-TrafficInfluSub
                    description: Created (Successful creation of subscription)
                    headers:
                        Location:
                            description: Contains the URI of the newly created resource
                            required: true
                            schema:
                                type: string
                "400":
                    $ref: TS29122_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29122_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29122_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29122_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29122_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29122_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29122_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29122_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29122_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29122_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Generic Error
            summary: Creates a new subscription resource
            tags:
                - Traffic Influence Subscription
    /{afId}/subscriptions/{subscriptionId}:
        parameters:
            - description: Identifier of the AF
              in: path
              name: afId
              required: true
              schema:
                type: string
            - description: Identifier of the subscription resource
              in: path
              name: subscriptionId
              required: true
              schema:
                type: string
        get:
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/TS29522-TrafficInfluSub
                    description: OK (Successful get the active subscription)
                "307":
                    $ref: TS29122_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29122_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29122_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29122_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29122_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29122_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29122_CommonData.yaml#/components/responses/406
                "429":
                    $ref: TS29122_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29122_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29122_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Generic Error
            summary: read an active subscriptions for the SCS/AS and the subscription Id
            tags:
                - Individual Traffic Influence Subscription
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/TS29522-TrafficInfluSub
                description: Parameters to update/replace the existing subscription
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/TS29522-TrafficInfluSub
                    description: OK (Successful update of the subscription)
                "307":
                    $ref: TS29122_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29122_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29122_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29122_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29122_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29122_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29122_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29122_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29122_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29122_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29122_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29122_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Generic Error
            summary: Updates/replaces an existing subscription resource
            tags:
                - Individual Traffic Influence Subscription
        delete:
            responses:
                "204":
                    description: No Content (Successful deletion of the existing subscription)
                "307":
                    $ref: TS29122_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29122_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29122_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29122_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29122_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29122_CommonData.yaml#/components/responses/404
                "429":
                    $ref: TS29122_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29122_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29122_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Generic Error
            summary: Deletes an already existing subscription
            tags:
                - Individual Traffic Influence Subscription
        patch:
            requestBody:
                content:
                    application/merge-patch+json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/TrafficInfluSubPatch
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/TS29522-TrafficInfluSub
                    description: OK. The subscription was modified successfully.
                "307":
                    $ref: TS29122_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29122_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29122_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29122_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29122_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29122_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29122_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29122_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29122_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29122_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29122_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29122_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Generic Error
            summary: Updates/replaces an existing subscription resource
            tags:
                - Individual Traffic Influence Subscription
security:
    - {}
    - oAuth2ClientCredentials: []
servers:
    - url: '{apiRoot}/3gpp-traffic-influence/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in subclause 5.2.4 of 3GPP TS 29.122.
