# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        namf-loc: Access to the Namf_Location API
externalDocs:
    description: 3GPP TS 29.518 V16.16.0; 5G System; Access and Mobility Management Services
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
info:
    description: |
        AMF Location Service
        © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Namf_Location
    version: 1.1.9
openapi: 3.0.0
paths:
    /{ueContextId}/cancel-pos-info:
        post:
            operationId: CancelLocation
            parameters:
                - description: UE Context Identifier
                  in: path
                  name: ueContextId
                  required: true
                  schema:
                    pattern: ^(imsi-[0-9]{5,15}|nai-.+|gli-.+|gci-.+|.+)$
                    type: string
                    x-go-type-skip-optional-pointer: true
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/CancelPosInfo
                required: true
            responses:
                "204":
                    description: Expected response to a successful cancellation
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                "504":
                    $ref: TS29571_CommonData.yaml#/components/responses/504
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Namf_Location CancelLocation service operation
            tags:
                - Individual UE context (Document)
    /{ueContextId}/provide-loc-info:
        post:
            operationId: ProvideLocationInfo
            parameters:
                - description: UE Context Identifier
                  in: path
                  name: ueContextId
                  required: true
                  schema:
                    pattern: ^(imsi-[0-9]{5,15}|nai-.+|gli-.+|gci-.+|imei-[0-9]{15}|imeisv-[0-9]{16}|.+)$
                    type: string
                    x-go-type-skip-optional-pointer: true
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/RequestLocInfo
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProvideLocInfo
                    description: Expected response to a valid request
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Namf_Location ProvideLocationInfo service Operation
            tags:
                - Individual UE context (Document)
    /{ueContextId}/provide-pos-info:
        post:
            callbacks:
                onUELocationNotification:
                    '{$request.body#/locationNotificationUri}':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/NotifiedPosInfo
                                description: UE Location Event Notification
                            responses:
                                "204":
                                    description: Expected response to a successful callback processing
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                "403":
                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
            operationId: ProvidePositioningInfo
            parameters:
                - description: UE Context Identifier
                  in: path
                  name: ueContextId
                  required: true
                  schema:
                    pattern: ^(imsi-[0-9]{5,15}|nai-.+|gli-.+|gci-.+|imei-[0-9]{15}|imeisv-[0-9]{16}|msisdn-[0-9]{5,15}|extid-.+@.+|.+)$
                    type: string
                    x-go-type-skip-optional-pointer: true
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/RequestPosInfo
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProvidePosInfo
                    description: Expected response to a valid request
                "204":
                    description: Successful accept of location request with no information returned.
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                "504":
                    $ref: TS29571_CommonData.yaml#/components/responses/504
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Namf_Location ProvidePositioningInfo service Operation
            tags:
                - Individual UE context (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - namf-loc
servers:
    - url: '{apiRoot}/namf-loc/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501
