# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        nudm-ueau: Access to the nudm-ueau API
externalDocs:
    description: 3GPP TS 29.503 Unified Data Management Services, version 16.12.0
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
info:
    description: "UDM UE Authentication Service.  \n© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
    title: Nudm_UEAU
    version: 1.1.3
openapi: 3.0.0
paths:
    /{supi}/auth-events:
        post:
            operationId: ConfirmAuth
            parameters:
                - description: SUPI of the user
                  in: path
                  name: supi
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/AuthEvent
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/AuthEvent
                    description: Expected response to a valid request
                    headers:
                        Location:
                            description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/nudm-ueau/v1/{supi}/auth-events/{authEventId}'
                            required: true
                            schema:
                                type: string
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Create a new confirmation event
            tags:
                - Confirm Auth
    /{supi}/auth-events/{authEventId}:
        put:
            operationId: DeleteAuth
            parameters:
                - description: SUPI of the user
                  in: path
                  name: supi
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
                - description: authEvent Id
                  in: path
                  name: authEventId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/AuthEvent
                required: true
            responses:
                "204":
                    description: Expected response to a successful authentication result removal
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Deletes the authentication result in the UDM
            tags:
                - Delete Auth
    /{supi}/hss-security-information/{hssAuthType}/generate-av:
        post:
            operationId: GenerateAv
            parameters:
                - description: SUPI of the user
                  in: path
                  name: supi
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
                - description: Type of AV requested by HSS
                  in: path
                  name: hssAuthType
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/HssAuthTypeInUri
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/HssAuthenticationInfoRequest
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/HssAuthenticationInfoResult
                    description: Expected response to a valid request
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "501":
                    $ref: TS29571_CommonData.yaml#/components/responses/501
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Generate authentication data for the UE in EPS or IMS domain
            tags:
                - Generate HSS Authentication Vectors
    /{supiOrSuci}/security-information-rg:
        get:
            operationId: GetRgAuthData
            parameters:
                - description: SUPI or SUCI of the user
                  in: path
                  name: supiOrSuci
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupiOrSuci
                - description: Authenticated indication
                  in: query
                  name: authenticated-ind
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/AuthenticatedInd
                - description: Supported Features
                  in: query
                  name: supported-features
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
                - content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
                  description: serving PLMN ID
                  in: query
                  name: plmn-id
                - description: Validator for conditional requests, as described in RFC 7232, 3.2
                  in: header
                  name: If-None-Match
                  schema:
                    type: string
                - description: Validator for conditional requests, as described in RFC 7232, 3.3
                  in: header
                  name: If-Modified-Since
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/RgAuthCtx
                    description: Expected response to a valid request
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Get authentication data for the FN-RG
            tags:
                - Get Auth Data for FN-RG
    /{supiOrSuci}/security-information/generate-auth-data:
        post:
            operationId: GenerateAuthData
            parameters:
                - description: SUPI or SUCI of the user
                  in: path
                  name: supiOrSuci
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupiOrSuci
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/AuthenticationInfoRequest
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/AuthenticationInfoResult
                    description: Expected response to a valid request
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "501":
                    $ref: TS29571_CommonData.yaml#/components/responses/501
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Generate authentication data for the UE
            tags:
                - Generate Auth Data
security:
    - oAuth2ClientCredentials:
        - nudm-ueau
    - {}
servers:
    - url: '{apiRoot}/nudm-ueau/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.
