# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        nudm-niddau: Access to the nudm-niddau API
externalDocs:
    description: 3GPP TS 29.503 Unified Data Management Services, version 16.13.0
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.503/
info:
    description: "Nudm NIDD Authorization Service.  \n© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
    title: Nudm_NIDDAU
    version: 1.0.3
openapi: 3.0.0
paths:
    /{ueIdentity}/authorize:
        post:
            callbacks:
                niddAuthUpdateNotification:
                    '{request.body#/authUpdateCallbackUri}':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/NiddAuthUpdateNotification
                                required: true
                            responses:
                                "204":
                                    description: Expected response to a valid request
            operationId: AuthorizeNiddData
            parameters:
                - description: Represents the scope of the UE for which the NIDD configuration are authorized. Contains the GPSI of the user or the external group ID.
                  in: path
                  name: ueIdentity
                  required: true
                  schema:
                    pattern: ^(msisdn-[0-9]{5,15}|.+|extid-[^@]+@[^@]+|extgroupid-[^@]+@[^@]+)$
                    type: string
                    x-go-type-skip-optional-pointer: true
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/AuthorizationInfo
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/AuthorizationData
                    description: Expected response to a valid request
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "501":
                    $ref: TS29571_CommonData.yaml#/components/responses/501
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Authorize the NIDD configuration request.
            tags:
                - Authorize the NIDD configuration request
security:
    - oAuth2ClientCredentials:
        - nudm-niddau
    - {}
servers:
    - url: '{apiRoot}/nudm-niddau/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.
