# This is generated file.

components:
    headers:
        cache-control:
            required: true
            schema:
                enum:
                    - no-store
                type: string
                x-go-type-skip-optional-pointer: true
        pragma:
            required: true
            schema:
                enum:
                    - no-cache
                type: string
                x-go-type-skip-optional-pointer: true
externalDocs:
    description: 3GPP TS 29.510 V16.11.0; 5G System; Network Function Repository Services; Stage 3
    url: https://www.3gpp.org/ftp/Specs/archive/29_series/29.510/
info:
    description: "NRF OAuth2 Authorization.  \n© 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  \nAll rights reserved.\n"
    title: NRF OAuth2
    version: 1.1.5
openapi: 3.0.0
paths:
    /oauth2/token:
        post:
            operationId: AccessTokenRequest
            parameters:
                - description: Content-Encoding, described in IETF RFC 7231
                  in: header
                  name: Content-Encoding
                  schema:
                    type: string
                - description: Accept-Encoding, described in IETF RFC 7231
                  in: header
                  name: Accept-Encoding
                  schema:
                    type: string
            requestBody:
                content:
                    application/x-www-form-urlencoded:
                        encoding:
                            requesterPlmn:
                                contentType: application/json
                            requesterPlmnList:
                                contentType: application/json
                            requesterSnpnList:
                                contentType: application/json
                            requesterSnssaiList:
                                contentType: application/json
                            targetNsiList:
                                explode: true
                                style: form
                            targetPlmn:
                                contentType: application/json
                            targetSnssaiList:
                                contentType: application/json
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/AccessTokenReq
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/AccessTokenRsp
                    description: Successful Access Token Request
                    headers:
                        Accept-Encoding:
                            description: Accept-Encoding, described in IETF RFC 7694
                            schema:
                                type: string
                        Cache-Control:
                            $ref: '#/components/headers/cache-control'
                        Content-Encoding:
                            description: Content-Encoding, described in IETF RFC 7231
                            schema:
                                type: string
                        Pragma:
                            $ref: '#/components/headers/pragma'
                "307":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/RedirectResponse
                    description: Temporary Redirect
                    headers:
                        Location:
                            description: The URI pointing to the resource located on the redirect target NRF
                            required: true
                            schema:
                                type: string
                "308":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/RedirectResponse
                    description: Permanent Redirect
                    headers:
                        Location:
                            description: The URI pointing to the resource located on the redirect target NRF
                            required: true
                            schema:
                                type: string
                "400":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/AccessTokenErr
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Error in the Access Token Request
                    headers:
                        Cache-Control:
                            $ref: '#/components/headers/cache-control'
                        Pragma:
                            $ref: '#/components/headers/pragma'
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "501":
                    $ref: TS29571_CommonData.yaml#/components/responses/501
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Access Token Request
            tags:
                - Access Token Request
