components:
    schemas:
        EthernetFlowInfo:
            additionalProperties: true
            properties:
                ethFlows:
                    items:
                        $ref: TS29514_Npcf_PolicyAuthorization.yaml#/components/schemas/EthFlowDescription
                    maxItems: 2
                    minItems: 1
                    type: array
                flowNumber:
                    type: integer
            required:
                - flowNumber
            type: object
        IpFlowInfo:
            additionalProperties: true
            properties:
                flowNumber:
                    type: integer
                ipFlows:
                    items:
                        $ref: TS29514_Npcf_PolicyAuthorization.yaml#/components/schemas/FlowDescription
                    maxItems: 2
                    minItems: 1
                    type: array
            required:
                - flowNumber
            type: object
        PcEvent:
            enum:
                - AC_TY_CH
                - PLMN_CH
            type: string
        PcEventExposureNotif:
            additionalProperties: true
            properties:
                eventNotifs:
                    items:
                        $ref: '#/components/schemas/PcEventNotification'
                    minItems: 1
                    type: array
                notifId:
                    type: string
            required:
                - notifId
                - eventNotifs
            type: object
        PcEventExposureSubsc:
            additionalProperties: true
            properties:
                eventSubs:
                    items:
                        $ref: '#/components/schemas/PcEvent'
                    minItems: 1
                    type: array
                eventsRepInfo:
                    $ref: '#/components/schemas/ReportingInformation'
                filterDnns:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Dnn
                    minItems: 1
                    type: array
                filterServices:
                    items:
                        $ref: '#/components/schemas/ServiceIdentification'
                    minItems: 1
                    type: array
                filterSnssais:
                    items:
                        $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
                    minItems: 1
                    type: array
                groupId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/GroupId
                notifId:
                    type: string
                notifUri:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Uri
                suppFeat:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - eventSubs
                - notifId
                - notifUri
            type: object
        PcEventNotification:
            additionalProperties: true
            properties:
                accType:
                    $ref: TS29571_CommonData.yaml#/components/schemas/AccessType
                addAccessInfo:
                    $ref: TS29512_Npcf_SMPolicyControl.yaml#/components/schemas/AdditionalAccessInfo
                anGwAddr:
                    $ref: TS29514_Npcf_PolicyAuthorization.yaml#/components/schemas/AnGwAddress
                event:
                    $ref: '#/components/schemas/PcEvent'
                gpsi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Gpsi
                pduSessionInfo:
                    $ref: '#/components/schemas/PduSessionInformation'
                plmnId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/PlmnIdNid
                ratType:
                    $ref: TS29571_CommonData.yaml#/components/schemas/RatType
                relAccessInfo:
                    $ref: TS29512_Npcf_SMPolicyControl.yaml#/components/schemas/AdditionalAccessInfo
                repServices:
                    $ref: '#/components/schemas/ServiceIdentification'
                supi:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
                timeStamp:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DateTime
            required:
                - event
                - timeStamp
            type: object
        PduSessionInformation:
            additionalProperties: true
            properties:
                dnn:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Dnn
                ipDomain:
                    type: string
                snssai:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Snssai
                ueIpv4:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ipv4Addr
                ueIpv6:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Ipv6Prefix
                ueMac:
                    $ref: TS29571_CommonData.yaml#/components/schemas/MacAddr48
            required:
                - snssai
                - dnn
            type: object
        ReportingInformation:
            additionalProperties: true
            properties:
                grpRepTime:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DurationSec
                immRep:
                    type: boolean
                maxReportNbr:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Uinteger
                monDur:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DateTime
                notifMethod:
                    $ref: TS29508_Nsmf_EventExposure.yaml#/components/schemas/NotificationMethod
                repPeriod:
                    $ref: TS29571_CommonData.yaml#/components/schemas/DurationSec
                sampRatio:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SamplingRatio
            type: object
        ServiceIdentification:
            additionalProperties: true
            properties:
                afAppId:
                    $ref: TS29514_Npcf_PolicyAuthorization.yaml#/components/schemas/AfAppId
                servEthFlows:
                    items:
                        $ref: '#/components/schemas/EthernetFlowInfo'
                    minItems: 1
                    type: array
                servIpFlows:
                    items:
                        $ref: '#/components/schemas/IpFlowInfo'
                    minItems: 1
                    type: array
            type: object
    securitySchemes:
        oAuth2ClientCredentials:
            flows:
                clientCredentials:
                    scopes:
                        npcf-eventexposure: Access to the Npcf_EventExposure API.
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
            type: oauth2
externalDocs:
    description: 3GPP TS 29.523 V16.5.0; 5G System; Policy Control Event Exposure Service; Stage 3.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.523/
info:
    description: |
        PCF Event Exposure Service.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Npcf_EventExposure
    version: 1.1.2
openapi: 3.0.0
paths:
    /subscriptions:
        post:
            callbacks:
                PcEventNotification:
                    '{$request.body#/notifUri}':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: '#/components/schemas/PcEventExposureNotif'
                                required: true
                            responses:
                                "204":
                                    description: No Content, Notification was succesfull
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                "401":
                                    $ref: TS29571_CommonData.yaml#/components/responses/401
                                "403":
                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                "404":
                                    $ref: TS29571_CommonData.yaml#/components/responses/404
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                default:
                                    $ref: TS29571_CommonData.yaml#/components/responses/default
            operationId: PostPcEventExposureSubsc
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PcEventExposureSubsc'
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PcEventExposureSubsc'
                    description: Success
                    headers:
                        Location:
                            description: 'Contains the URI of the created individual policy control events subscription resource, according to the structure: {apiRoot}/npcf-eventexposure/v1/subscriptions/{subscriptionId}'
                            required: true
                            schema:
                                type: string
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Creates a new Individual Policy Control Events Subscription resource
            tags:
                - Policy Control Events Subscription (Collection)
    /subscriptions/{subscriptionId}:
        delete:
            operationId: DeletePcEventExposureSubsc
            parameters:
                - description: Policy Control Event Subscription ID
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: No Content. Resource was succesfully deleted
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: 'Cancels an existing Individual Policy Control Events Subscription '
            tags:
                - Individual Policy Control Events Subscription (Document)
        get:
            operationId: GetPcEventExposureSubsc
            parameters:
                - description: Policy Control Event Subscription ID
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PcEventExposureSubsc'
                    description: OK. Resource representation is returned
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29571_CommonData.yaml#/components/responses/406
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Reads an existing Individual Policy Control Events Subscription
            tags:
                - Individual Policy Control Events Subscription (Document)
        put:
            operationId: PutPcEventExposureSubsc
            parameters:
                - description: Policy Control Event Subscription ID
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/PcEventExposureSubsc'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PcEventExposureSubsc'
                    description: OK. Resource was succesfully modified and representation is returned
                "204":
                    description: No Content. Resource was succesfully modified
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: 'Modifies an existing Individual Policy Control Events Subscription '
            tags:
                - Individual Policy Control Events Subscription (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - npcf-eventexposure
servers:
    - url: '{apiRoot}/npcf-eventexposure/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501
