components:
    schemas:
        AccessTech:
            enum:
                - NR
                - EUTRAN_IN_WBS1_MODE_AND_NBS1_MODE
                - EUTRAN_IN_NBS1_MODE_ONLY
                - EUTRAN_IN_WBS1_MODE_ONLY
                - UTRAN
                - GSM_AND_ECGSM_IoT
                - GSM_WITHOUT_ECGSM_IoT
                - ECGSM_IoT_ONLY
                - CDMA_1xRTT
                - CDMA_HRPD
                - GSM_COMPACT
            type: string
        AckInd:
            type: boolean
        CounterSor:
            pattern: ^[A-Fa-f0-9]{4}$
            type: string
            x-go-type-skip-optional-pointer: true
        SecuredPacket:
            format: base64
            type: string
        SorInfo:
            additionalProperties: true
            properties:
                ackInd:
                    $ref: '#/components/schemas/AckInd'
                steeringContainer:
                    $ref: '#/components/schemas/SteeringContainer'
                supportedFeatures:
                    $ref: TS29571_CommonData.yaml#/components/schemas/SupportedFeatures
            required:
                - ackInd
            type: object
        SorMac:
            pattern: ^[A-Fa-f0-9]{32}$
            type: string
            x-go-type-skip-optional-pointer: true
        SorSecurityInfo:
            additionalProperties: true
            properties:
                counterSor:
                    $ref: '#/components/schemas/CounterSor'
                sorMacIausf:
                    $ref: '#/components/schemas/SorMac'
                sorXmacIue:
                    $ref: '#/components/schemas/SorMac'
            required:
                - sorMacIausf
                - counterSor
            type: object
        SteeringContainer:
            oneOf:
                - items:
                    $ref: '#/components/schemas/SteeringInfo'
                  minItems: 1
                  type: array
                  x-go-type-skip-optional-pointer: true
                - $ref: '#/components/schemas/SecuredPacket'
        SteeringInfo:
            additionalProperties: true
            properties:
                accessTechList:
                    items:
                        $ref: '#/components/schemas/AccessTech'
                    minItems: 1
                    type: array
                    x-go-type-skip-optional-pointer: true
                plmnId:
                    $ref: TS29571_CommonData.yaml#/components/schemas/PlmnId
            required:
                - plmnId
            type: object
    securitySchemes:
        oAuth2ClientCredentials:
            flows:
                clientCredentials:
                    scopes:
                        nausf-sorprotection: Access to the Nausf_SoRProtection API
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
            type: oauth2
externalDocs:
    description: 3GPP TS 29.509 V16.9.0; 5G System; Authentication Server Services
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.509
info:
    description: |
        AUSF SoR Protection Service.
        © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Nausf_SoRProtection Service
    version: 1.1.3
openapi: 3.0.0
paths:
    /{supi}/ue-sor:
        post:
            parameters:
                - description: Identifier of the UE
                  in: path
                  name: supi
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SorInfo'
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SorSecurityInfo'
                    description: SorSecurityInfo
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "503":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Service Unavailable
security:
    - {}
    - oAuth2ClientCredentials:
        - nausf-sorprotection
servers:
    - url: '{apiRoot}/nausf-sorprotection/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.
