# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        nausf-sorprotection: Access to the Nausf_SoRProtection API
externalDocs:
    description: 3GPP TS 29.509 V16.9.0; 5G System; Authentication Server Services
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.509
info:
    description: |
        AUSF SoR Protection Service.
        © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Nausf_SoRProtection Service
    version: 1.1.3
openapi: 3.0.0
paths:
    /{supi}/ue-sor:
        post:
            parameters:
                - description: Identifier of the UE
                  in: path
                  name: supi
                  required: true
                  schema:
                    $ref: TS29571_CommonData.yaml#/components/schemas/Supi
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/ausf-SorInfo
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/SorSecurityInfo
                    description: SorSecurityInfo
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "503":
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Service Unavailable
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: ""
security:
    - {}
    - oAuth2ClientCredentials:
        - nausf-sorprotection
servers:
    - url: '{apiRoot}/nausf-sorprotection/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501.
