# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        namf-evts: Access to the Namf_EventExposure API
externalDocs:
    description: 3GPP TS 29.518 V16.13.0; 5G System; Access and Mobility Management Services
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.518/
info:
    description: |
        AMF Event Exposure Service
        © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Namf_EventExposure
    version: 1.1.8
openapi: 3.0.0
paths:
    /subscriptions:
        post:
            callbacks:
                onEventReport:
                    '{$request.body#/subscription/eventNotifyUri}':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/AmfEventNotification
                                required: true
                            responses:
                                "204":
                                    description: Successful acknowledgement
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                "401":
                                    $ref: TS29571_CommonData.yaml#/components/responses/401
                                "403":
                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                "404":
                                    $ref: TS29571_CommonData.yaml#/components/responses/404
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                default:
                                    description: Unexpected error
                            summary: Event Notificaiton Delivery
                onSubscriptionIdChangeEvtReport:
                    '{$request.body#/subscription/subsChangeNotifyUri}':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/AmfEventNotification
                                required: true
                            responses:
                                "204":
                                    description: Successful acknowledgement
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                default:
                                    description: Unexpected error
                            summary: Event Notificaiton Delivery For Subscription Id Change
            operationId: CreateSubscription
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/AmfCreateEventSubscription
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/AmfCreatedEventSubscription
                    description: Subsription Created
                    headers:
                        Location:
                            description: 'Contains the URI of the newly created resource, according to the structure: {apiRoot}/namf-evts/<apiVersion>/subscriptions/{subscriptionId}'
                            required: true
                            schema:
                                type: string
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Namf_EventExposure Subscribe service Operation
            tags:
                - Subscriptions collection (Document)
    /subscriptions/{subscriptionId}:
        delete:
            operationId: DeleteSubscription
            parameters:
                - description: Unique ID of the subscription to be deleted
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: Subsription deleted successfully
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Namf_EventExposure Unsubscribe service Operation
            tags:
                - Individual subscription (Document)
        patch:
            operationId: ModifySubscription
            parameters:
                - description: Unique ID of the subscription to be modified
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json-patch+json:
                        schema:
                            oneOf:
                                - items:
                                    $ref: TS29571_CommonData.yaml#/components/schemas/AmfUpdateEventSubscriptionItem
                                  minItems: 1
                                  type: array
                                  x-go-type-skip-optional-pointer: true
                                - items:
                                    $ref: TS29571_CommonData.yaml#/components/schemas/AmfUpdateEventOptionItem
                                  maxItems: 1
                                  minItems: 1
                                  type: array
                                  x-go-type-skip-optional-pointer: true
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/AmfUpdatedEventSubscription
                    description: Subsription modified successfully
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    content:
                        application/problem+json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/ProblemDetails
                    description: Unexpected error
            summary: Namf_EventExposure Subscribe Modify service Operation
            tags:
                - Individual subscription (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - namf-evts
servers:
    - url: '{apiRoot}/namf-evts/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in clause clause 4.4 of 3GPP TS 29.501
