# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        npcf-bdtpolicycontrol: Access to the Npcf_BDTPolicyControl API
externalDocs:
    description: 3GPP TS 29.554 V16.7.0; 5G System; Background Data Transfer Policy Control Service.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.554/
info:
    description: |
        PCF BDT Policy Control Service.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Npcf_BDTPolicyControl Service API
    version: 1.1.3
openapi: 3.0.0
paths:
    /bdtpolicies:
        post:
            callbacks:
                BdtNotification:
                    '{$request.body#/notifUri}':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/Notification
                                required: true
                            responses:
                                "204":
                                    description: No Content, a reception of the BDT notification was successful.
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                "401":
                                    $ref: TS29571_CommonData.yaml#/components/responses/401
                                "403":
                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                "404":
                                    $ref: TS29571_CommonData.yaml#/components/responses/404
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                default:
                                    $ref: TS29571_CommonData.yaml#/components/responses/default
            operationId: CreateBDTPolicy
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/BdtReqData
                description: Contains information for the creation of a new Individual BDT policy resource.
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/BdtPolicy
                    description: Background data transfer policies offered to an ASP.
                    headers:
                        Location:
                            description: 'Contains the URI of the created individual BDT policy resource, according to the structure: {apiRoot}/npcf-bdtpolicycontrol/v1/bdtpolicies/{bdtPolicyId}'
                            required: true
                            schema:
                                type: string
                "303":
                    description: See Other. The result of the POST request would be equivalent to the existing Individual BDT policy resource.
                    headers:
                        Location:
                            description: Contains the URI of the existing individual BDT policy resource.
                            required: true
                            schema:
                                type: string
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Create a new Individual BDT policy
            tags:
                - BDT policies (Collection)
    /bdtpolicies/{bdtPolicyId}:
        get:
            operationId: GetBDTPolicy
            parameters:
                - description: String identifying the individual BDT policy resource in the PCF.
                  in: path
                  name: bdtPolicyId
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/BdtPolicy
                    description: Background data transfer policies offered to and selected by an ASP.
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29571_CommonData.yaml#/components/responses/406
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Read an Individual BDT policy
            tags:
                - Individual BDT policy (Document)
        patch:
            operationId: UpdateBDTPolicy
            parameters:
                - description: String identifying the individual BDT policy resource in the PCF.
                  in: path
                  name: bdtPolicyId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/merge-patch+json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/PatchBdtPolicy
                description: Contains modification instruction to be performed on the BdtPolicy data structure to select a transfer policy and in addition, may indicate whether the BDT warning notification is enabled or disabled.
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/BdtPolicy
                    description: The Individual BDT Policy resource is modified and a representation of that resource is returned.
                "204":
                    description: The Individual BDT Policy resource is modified.
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Update an Individual BDT policy
            tags:
                - Individual BDT policy (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - npcf-bdtpolicycontrol
servers:
    - url: '{apiRoot}/npcf-bdtpolicycontrol/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501.
