# This is generated file.

components:
    securitySchemes:
        oAuth2ClientCredentials:
            type: oauth2
            flows:
                clientCredentials:
                    tokenUrl: '{nrfApiRoot}/oauth2/token'
                    scopes:
                        npcf-eventexposure: Access to the Npcf_EventExposure API.
externalDocs:
    description: 3GPP TS 29.523 V16.5.0; 5G System; Policy Control Event Exposure Service; Stage 3.
    url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.523/
info:
    description: |
        PCF Event Exposure Service.
        © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
        All rights reserved.
    title: Npcf_EventExposure
    version: 1.1.2
openapi: 3.0.0
paths:
    /subscriptions:
        post:
            callbacks:
                PcEventNotification:
                    '{$request.body#/notifUri}':
                        post:
                            requestBody:
                                content:
                                    application/json:
                                        schema:
                                            $ref: TS29571_CommonData.yaml#/components/schemas/PcEventExposureNotif
                                required: true
                            responses:
                                "204":
                                    description: No Content, Notification was succesfull
                                "307":
                                    $ref: TS29571_CommonData.yaml#/components/responses/307
                                "308":
                                    $ref: TS29571_CommonData.yaml#/components/responses/308
                                "400":
                                    $ref: TS29571_CommonData.yaml#/components/responses/400
                                "401":
                                    $ref: TS29571_CommonData.yaml#/components/responses/401
                                "403":
                                    $ref: TS29571_CommonData.yaml#/components/responses/403
                                "404":
                                    $ref: TS29571_CommonData.yaml#/components/responses/404
                                "411":
                                    $ref: TS29571_CommonData.yaml#/components/responses/411
                                "413":
                                    $ref: TS29571_CommonData.yaml#/components/responses/413
                                "415":
                                    $ref: TS29571_CommonData.yaml#/components/responses/415
                                "429":
                                    $ref: TS29571_CommonData.yaml#/components/responses/429
                                "500":
                                    $ref: TS29571_CommonData.yaml#/components/responses/500
                                "503":
                                    $ref: TS29571_CommonData.yaml#/components/responses/503
                                default:
                                    $ref: TS29571_CommonData.yaml#/components/responses/default
            operationId: PostPcEventExposureSubsc
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/PcEventExposureSubsc
                required: true
            responses:
                "201":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/PcEventExposureSubsc
                    description: Success
                    headers:
                        Location:
                            description: 'Contains the URI of the created individual policy control events subscription resource, according to the structure: {apiRoot}/npcf-eventexposure/v1/subscriptions/{subscriptionId}'
                            required: true
                            schema:
                                type: string
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Creates a new Individual Policy Control Events Subscription resource
            tags:
                - Policy Control Events Subscription (Collection)
    /subscriptions/{subscriptionId}:
        get:
            operationId: GetPcEventExposureSubsc
            parameters:
                - description: Policy Control Event Subscription ID
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                    type: string
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/PcEventExposureSubsc
                    description: OK. Resource representation is returned
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "406":
                    $ref: TS29571_CommonData.yaml#/components/responses/406
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: Reads an existing Individual Policy Control Events Subscription
            tags:
                - Individual Policy Control Events Subscription (Document)
        put:
            operationId: PutPcEventExposureSubsc
            parameters:
                - description: Policy Control Event Subscription ID
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                    type: string
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: TS29571_CommonData.yaml#/components/schemas/PcEventExposureSubsc
                required: true
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: TS29571_CommonData.yaml#/components/schemas/PcEventExposureSubsc
                    description: OK. Resource was succesfully modified and representation is returned
                "204":
                    description: No Content. Resource was succesfully modified
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "411":
                    $ref: TS29571_CommonData.yaml#/components/responses/411
                "413":
                    $ref: TS29571_CommonData.yaml#/components/responses/413
                "415":
                    $ref: TS29571_CommonData.yaml#/components/responses/415
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: 'Modifies an existing Individual Policy Control Events Subscription '
            tags:
                - Individual Policy Control Events Subscription (Document)
        delete:
            operationId: DeletePcEventExposureSubsc
            parameters:
                - description: Policy Control Event Subscription ID
                  in: path
                  name: subscriptionId
                  required: true
                  schema:
                    type: string
            responses:
                "204":
                    description: No Content. Resource was succesfully deleted
                "307":
                    $ref: TS29571_CommonData.yaml#/components/responses/307
                "308":
                    $ref: TS29571_CommonData.yaml#/components/responses/308
                "400":
                    $ref: TS29571_CommonData.yaml#/components/responses/400
                "401":
                    $ref: TS29571_CommonData.yaml#/components/responses/401
                "403":
                    $ref: TS29571_CommonData.yaml#/components/responses/403
                "404":
                    $ref: TS29571_CommonData.yaml#/components/responses/404
                "429":
                    $ref: TS29571_CommonData.yaml#/components/responses/429
                "500":
                    $ref: TS29571_CommonData.yaml#/components/responses/500
                "503":
                    $ref: TS29571_CommonData.yaml#/components/responses/503
                default:
                    $ref: TS29571_CommonData.yaml#/components/responses/default
            summary: 'Cancels an existing Individual Policy Control Events Subscription '
            tags:
                - Individual Policy Control Events Subscription (Document)
security:
    - {}
    - oAuth2ClientCredentials:
        - npcf-eventexposure
servers:
    - url: '{apiRoot}/npcf-eventexposure/v1'
      variables:
        apiRoot:
            default: https://example.com
            description: apiRoot as defined in subclause 4.4 of 3GPP TS 29.501
