// Package commondata provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.1-0.20240123090344-d326c01d279a DO NOT EDIT.
package commondata

import (
	externalRef0 "github.com/ShouheiNishi/openapi5g/models"
)

// N400 defines model for 400.
type N400 = externalRef0.TS29122ProblemDetails

// N401 defines model for 401.
type N401 = externalRef0.TS29122ProblemDetails

// N403 defines model for 403.
type N403 = externalRef0.TS29122ProblemDetails

// N404 defines model for 404.
type N404 = externalRef0.TS29122ProblemDetails

// N406 defines model for 406.
type N406 = externalRef0.TS29122ProblemDetails

// N409 defines model for 409.
type N409 = externalRef0.TS29122ProblemDetails

// N411 defines model for 411.
type N411 = externalRef0.TS29122ProblemDetails

// N412 defines model for 412.
type N412 = externalRef0.TS29122ProblemDetails

// N413 defines model for 413.
type N413 = externalRef0.TS29122ProblemDetails

// N414 defines model for 414.
type N414 = externalRef0.TS29122ProblemDetails

// N415 defines model for 415.
type N415 = externalRef0.TS29122ProblemDetails

// N429 defines model for 429.
type N429 = externalRef0.TS29122ProblemDetails

// N500 defines model for 500.
type N500 = externalRef0.TS29122ProblemDetails

// N503 defines model for 503.
type N503 = externalRef0.TS29122ProblemDetails

type N307ResponseHeaders struct {
	Location string
}
type N307Response struct {
	Headers N307ResponseHeaders
}

type N308ResponseHeaders struct {
	Location string
}
type N308Response struct {
	Headers N308ResponseHeaders
}

type N400ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N401ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N403ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N404ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N406ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N409ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N411ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N412ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N413ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N414ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N415ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N429ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N500ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type N503ApplicationProblemPlusJSONResponse externalRef0.TS29122ProblemDetails

type DefaultResponse struct {
}
