package: middleware_test
generate:
  models: true
  client: true
  gin-server: true
  strict-server: true
output-options:
  skip-prune: true
import-mapping:
  ../../../modSpecs/TS29571_CommonData.yaml: github.com/ShouheiNishi/openapi5g/models
output: middleware.gen_test.go
