// Code generated by github.com/ShouheiNishi/openapi5g/internal/generator, DO NOT EDIT.

package authorization

//go:generate go run github.com/deepmap/oapi-codegen/cmd/oapi-codegen --config=config.yaml ../../modSpecs/TS29514_Npcf_PolicyAuthorization.yaml
