name: govulncheck

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 16 * * *'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: golang-govulncheck-action
      uses: golang/govulncheck-action@v1.0.1
      with:
        go-version-input: '1.21.x'
        check-latest: true
